### 크리에이터 등록
POST localhost:8080/api/creators/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjcm91bmRAY3JvdW5kLmNvbSIsImV4cCI6MTY4NDQyNTE4MCwiaWF0IjoxNjg0NDE3OTgwfQ.RGALnF0lQUZxbEeTN_AcxuUO8_pLyjaqJ6a9kMj5gI0

{
  "profileImage": "profle image",
  "platformUrl": "https://www.youtube.com/",
  "platformType": "YOUTUBE",
  "platformActivityName": "유튜버",
  "tags": [
    {"tagName": "나는야"},
    {"tagName": "유튜버"},
    {"tagName": "크리에이터"}
  ]
}