### 크리에이터 등록
POST localhost:8080/api/creators/1
Content-Type: application/json

{
  "profileImage": "profle image",
  "platformUrl": "https://www.youtube.com/",
  "platformType": "YOUTUBE",
  "platformActivityName": "유튜버",
  "tags": [
    {"tagName": "나는야"},
    {"tagName": "유튜버"},
    {"tagName": "크리에이터"}
  ]
}