### 회원가입
POST localhost:8080/api/members
Content-Type: application/json

{
  "email": "cround@cround.com",
  "username": "크라운드",
  "nickname": "크라운드",
  "password": "cround",
  "confirmPassword": "cround",
  "interestPlatform": ["YOUTUBE", "TIKTOK"]
}

### 회원가입
POST localhost:8080/api/members
Content-Type: application/json

{
  "email": "cround1@cround.com",
  "username": "크라운드",
  "nickname": "크라운드1",
  "password": "cround",
  "confirmPassword": "cround",
  "interestPlatform": ["YOUTUBE", "TIKTOK"]
}

### 일반 로그인
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "cround@cround.com",
  "password": "cround"
}

### 팔로우
POST localhost:8080/api/members/following
Content-Type: application/json

{
  "sourceId": 2,
  "targetId": 1
}

### 언팔로우
DELETE localhost:8080/api/members/following
Content-Type: application/json

{
  "sourceId": 2,
  "targetId": 1
}

### 소셜 로그인
GET localhost:8080/cround/auth
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWVzYTUyMjFAZ21haWwuY29tIiwiZXhwIjoxNjgzNzMzMTczLCJpYXQiOjE2ODM3MjU5NzN9.DzIhu4WLWxUuHWnPOi1aLmAFHlUki5zawh1XDu0vQO4
